//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLDiemSinhVien.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDiemSVNTTEntities : DbContext
    {
        public QLDiemSVNTTEntities()
            : base("name=QLDiemSVNTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENNGANH> CHUYENNGANHs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MON> MONs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<thongtindiemsinhvien> thongtindiemsinhviens { get; set; }
        public virtual DbSet<DIEM> DIEMs { get; set; }
    
        public virtual ObjectResult<TIMKIEM_Result> TIMKIEM(string mSSV, string mAMON, string mACN)
        {
            var mSSVParameter = mSSV != null ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(string));
    
            var mAMONParameter = mAMON != null ?
                new ObjectParameter("MAMON", mAMON) :
                new ObjectParameter("MAMON", typeof(string));
    
            var mACNParameter = mACN != null ?
                new ObjectParameter("MACN", mACN) :
                new ObjectParameter("MACN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TIMKIEM_Result>("TIMKIEM", mSSVParameter, mAMONParameter, mACNParameter);
        }
    
        public virtual int SUASV(string mASV, Nullable<double> dIEMTHUONGKI, Nullable<double> dIEMTHUCHANH, Nullable<double> dIEMGIUAKI, Nullable<double> dIEMTHI, Nullable<double> dIEMTONGKET, string tHANGDIEM4, string gHICHU)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var dIEMTHUONGKIParameter = dIEMTHUONGKI.HasValue ?
                new ObjectParameter("DIEMTHUONGKI", dIEMTHUONGKI) :
                new ObjectParameter("DIEMTHUONGKI", typeof(double));
    
            var dIEMTHUCHANHParameter = dIEMTHUCHANH.HasValue ?
                new ObjectParameter("DIEMTHUCHANH", dIEMTHUCHANH) :
                new ObjectParameter("DIEMTHUCHANH", typeof(double));
    
            var dIEMGIUAKIParameter = dIEMGIUAKI.HasValue ?
                new ObjectParameter("DIEMGIUAKI", dIEMGIUAKI) :
                new ObjectParameter("DIEMGIUAKI", typeof(double));
    
            var dIEMTHIParameter = dIEMTHI.HasValue ?
                new ObjectParameter("DIEMTHI", dIEMTHI) :
                new ObjectParameter("DIEMTHI", typeof(double));
    
            var dIEMTONGKETParameter = dIEMTONGKET.HasValue ?
                new ObjectParameter("DIEMTONGKET", dIEMTONGKET) :
                new ObjectParameter("DIEMTONGKET", typeof(double));
    
            var tHANGDIEM4Parameter = tHANGDIEM4 != null ?
                new ObjectParameter("THANGDIEM4", tHANGDIEM4) :
                new ObjectParameter("THANGDIEM4", typeof(string));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUASV", mASVParameter, dIEMTHUONGKIParameter, dIEMTHUCHANHParameter, dIEMGIUAKIParameter, dIEMTHIParameter, dIEMTONGKETParameter, tHANGDIEM4Parameter, gHICHUParameter);
        }
    
        public virtual int XOADIEM(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOADIEM", mASVParameter);
        }
    }
}
