//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLDiemSinhVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string MaGV { get; set; }
        public string HocKi { get; set; }
        public string MSCN { get; set; }
        public string MaSV { get; set; }
    
        public virtual CHUYENNGANH CHUYENNGANH { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
    }
}
